export const data=[
    {
        key:'1',
        category:"Java",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/28.jpg",
        title:"heyo mething excited and its is a java feature so you have to learn it ",
        description:"A card can java Java is a general-purpose programming language that is class-based Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere (WORA),[16] meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.[17] Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of the underlying computer architecture. The syntax of Java is similar to C and C++, but it has fewer low-level facilities than either of them. As of 2019, Java was one of the most popular programming languages in use according to GitHub,[18][19] particularly for client-server web applications, with a reported 9 million developers",
    },
    {
        key:'2',
        category:"Python",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/26.jpg",
        title:"heyo mething python Java is a general-purpose programming language that is class-based",
        description:"A card can  style Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere (WORA),[16] meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.[17] Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of the underlying computer architecture. The syntax of Java is similar to C and C++, but it has fewer low-level facilities than either of them. As of 2019, Java was one of the most popular programming languages in use according to GitHub,[18][19] particularly for client-server web applications, with a reported 9 million developers",
    },
    {
        key:'3',
        category:"C",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/27.jpg",
        title:"heyo C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, while a static type system prevents unintended operations mething c/c++",
        description:"A card can rows: 3,As an imperative language, C uses statements to specify actions. The most common statement is an expression statement, consisting of an expression to be evaluated, followed by a semicolon; as a side effect of the evaluation, functions may be called and variables may be assigned new values. To modify the normal sequential execution of statements, C provides several control-flow statements identified by reserved keywords. Structured programming is supported by if(-else) conditional execution and by do-while, while, and for iterative execution (looping). The for statement has separate initialization, testing, and reinitialization expressions, any or all of which can be omitted. break and continue can be used to leave the innermost enclosing loop statement or skip to its reinitialization. There is also a non-structured goto statement which branches directly to the designated label within the function. switch selects a case to be executed based on the value of an integer expression. style",
    },
    {
        key:'4',
        category:"DSA",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/19.jpg",
        title:"heyo mething dsa Java is a general-purpose programming language that is class-based",
        description:"A card can  style Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere (WORA),[16] meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.[17] Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of the underlying computer architecture. The syntax of Java is similar to C and C++, but it has fewer low-level facilities than either of them. As of 2019, Java was one of the most popular programming languages in use according to GitHub,[18][19] particularly for client-server web applications, with a reported 9 million developers",
    },
    {
        key:'5',
        category:'Machine_learning',
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/21.jpg",
        title:"heyo m learning Python is an interpreted, high-level, general-purpose programming language.",
        description:"A  As an imperative language, C uses statements to specify actions. The most common statement is an expression statement, consisting of an expression to be evaluated, followed by a semicolon; as a side effect of the evaluation, functions may be called and variables may be assigned new values. To modify the normal sequential execution of statements, C provides several control-flow statements identified by reserved keywords. Structured programming is supported by if(-else) conditional execution and by do-while, while, and for iterative execution (looping). The for statement has separate initialization, testing, and reinitialization expressions, any or all of which can be omitted. break and continue can be used to leave the innermost enclosing loop statement or skip to its reinitialization. There is also a non-structured goto statement which branches directly to the designated label within the function. switch selects a case to be executed based on the value of an integer expression.card can  style",
    },
    {
        key:'7',
        category:"Java",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/29.jpg",
        title:"heyo mething excited java Java is a general-purpose programming language that is class-based Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere (WORA),[16] meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.[17] Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of the underlying computer architecture. The syntax of Java is similar to C and C++, but it has fewer low-level facilities than either of them. As of 2019, Java was one of the most popular programming languages in use according to GitHub,[18][19] particularly for client-server web applications, with a reported 9 million developers",
        description:"A As an imperative language, C uses statements to specify actions. The most common statement is an expression statement, consisting of an expression to be evaluated, followed by a semicolon; as a side effect of the evaluation, functions may be called and variables may be assigned new values. To modify the normal sequential execution of statements, C provides several control-flow statements identified by reserved keywords. Structured programming is supported by if(-else) conditional execution and by do-while, while, and for iterative execution (looping). The for statement has separate initialization, testing, and reinitialization expressions, any or all of which can be omitted. break and continue can be used to leave the innermost enclosing loop statement or skip to its reinitialization. There is also a non-structured goto statement which branches directly to the designated label within the function. switch selects a case to be executed based on the value of an integer expression. card can java",
    },
    {
        key:'8',
        category:"Python",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/13.jpg",
        title:"heyo mething python Python is an interpreted, high-level, general-purpose programming language.",
        description:"A card can  style Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology.",
    },
    {
        key:'59',
        category:"C",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/23.jpg",
        title:"C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, while a static type system prevents unintended operations heyo mething c/c++",
        description:"A As an imperative language, C uses statements to specify actions. The most common statement is an expression statement, consisting of an expression to be evaluated, followed by a semicolon; as a side effect of the evaluation, functions may be called and variables may be assigned new values. To modify the normal sequential execution of statements, C provides several control-flow statements identified by reserved keywords. Structured programming is supported by if(-else) conditional execution and by do-while, while, and for iterative execution (looping). The for statement has separate initialization, testing, and reinitialization expressions, any or all of which can be omitted. break and continue can be used to leave the innermost enclosing loop statement or skip to its reinitialization. There is also a non-structured goto statement which branches directly to the designated label within the function. switch selects a case to be executed based on the value of an integer expression.card can  style",
    },
    {
        key:'30',
        category:"DSA",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/24.jpg",
        title:"heyo C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, while a static type system prevents unintended operations mething dsa ",
        description:"A As an imperative language, C uses statements to specify actions. The most common statement is an expression statement, consisting of an expression to be evaluated, followed by a semicolon; as a side effect of the evaluation, functions may be called and variables may be assigned new values. To modify the normal sequential execution of statements, C provides several control-flow statements identified by reserved keywords. Structured programming is supported by if(-else) conditional execution and by do-while, while, and for iterative execution (looping). The for statement has separate initialization, testing, and reinitialization expressions, any or all of which can be omitted. break and continue can be used to leave the innermost enclosing loop statement or skip to its reinitialization. There is also a non-structured goto statement which branches directly to the designated label within the function. switch selects a case to be executed based on the value of an integer expression. card can  style",
    },
    {
        key:'31',
        category:"Java",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/28.jpg",
        title:"heyo mething excited java Java is a general-purpose programming language that is class-based",
        description:"A card can java Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere (WORA),[16] meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.[17] Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of the underlying computer architecture. The syntax of Java is similar to C and C++, but it has fewer low-level facilities than either of them. As of 2019, Java was one of the most popular programming languages in use according to GitHub,[18][19] particularly for client-server web applications, with a reported 9 million developers ",
    },
    {
        key:'32',
        category:"Python",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/26.jpg",
        title:"heyo mething python Python is an interpreted, high-level, general-purpose programming language. ",
        description:"A card can  style Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology.",
    },
    {
        key:'33',
        category:"C",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/27.jpg",
        title:"heyo C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, while a static type system prevents unintended operations mething c/c++",
        description:"A As an imperative language, C uses statements to specify actions. The most common statement is an expression statement, consisting of an expression to be evaluated, followed by a semicolon; as a side effect of the evaluation, functions may be called and variables may be assigned new values. To modify the normal sequential execution of statements, C provides several control-flow statements identified by reserved keywords. Structured programming is supported by if(-else) conditional execution and by do-while, while, and for iterative execution (looping). The for statement has separate initialization, testing, and reinitialization expressions, any or all of which can be omitted. break and continue can be used to leave the innermost enclosing loop statement or skip to its reinitialization. There is also a non-structured goto statement which branches directly to the designated label within the function. switch selects a case to be executed based on the value of an integer expression. card can  style",
    },
    {
        key:'34',
        category:"DSA",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/19.jpg",
        title:"heyo mething dsa C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, while a static type system prevents unintended operations ",
        description:"A As an imperative language, C uses statements to specify actions. The most common statement is an expression statement, consisting of an expression to be evaluated, followed by a semicolon; as a side effect of the evaluation, functions may be called and variables may be assigned new values. To modify the normal sequential execution of statements, C provides several control-flow statements identified by reserved keywords. Structured programming is supported by if(-else) conditional execution and by do-while, while, and for iterative execution (looping). The for statement has separate initialization, testing, and reinitialization expressions, any or all of which can be omitted. break and continue can be used to leave the innermost enclosing loop statement or skip to its reinitialization. There is also a non-structured goto statement which branches directly to the designated label within the function. switch selects a case to be executed based on the value of an integer expression. card can  style",
    },
    {
        key:'35',
        category:'Machine_learning',
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/21.jpg",
        title:"heyo m learning Python is an interpreted, high-level, general-purpose programming language.",
        description:"A card can  style Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology.",
    },
    {
        key:'37',
        category:"Java",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/29.jpg",
        title:"heyo excited java Java is a general-purpose programming language that is class-based",
        description:"A card can java Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere (WORA),[16] meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.[17] Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of the underlying computer architecture. The syntax of Java is similar to C and C++, but it has fewer low-level facilities than either of them. As of 2019, Java was one of the most popular programming languages in use according to GitHub,[18][19] particularly for client-server web applications, with a reported 9 million developers",
    },
    {
        key:'38',
        category:"Python",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/13.jpg",
        title:"heyo mething python Python is an interpreted, high-level, general-purpose programming language.",
        description:"A card can  style Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology.",
    },
    {
        key:'39',
        category:"C",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/23.jpg",
        title:"heyo mething c/c++ C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, while a static type system prevents unintended operations",
        description:"A As an imperative language, C uses statements to specify actions. The most common statement is an expression statement, consisting of an expression to be evaluated, followed by a semicolon; as a side effect of the evaluation, functions may be called and variables may be assigned new values. To modify the normal sequential execution of statements, C provides several control-flow statements identified by reserved keywords. Structured programming is supported by if(-else) conditional execution and by do-while, while, and for iterative execution (looping). The for statement has separate initialization, testing, and reinitialization expressions, any or all of which can be omitted. break and continue can be used to leave the innermost enclosing loop statement or skip to its reinitialization. There is also a non-structured goto statement which branches directly to the designated label within the function. switch selects a case to be executed based on the value of an integer expression.card can  style",
    },
    {
        key:'40',
        category:"DSA",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/24.jpg",
        title:"heyo mething dsa C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, while a static type system prevents unintended operations",
        description:"A As an imperative language, C uses statements to specify actions. The most common statement is an expression statement, consisting of an expression to be evaluated, followed by a semicolon; as a side effect of the evaluation, functions may be called and variables may be assigned new values. To modify the normal sequential execution of statements, C provides several control-flow statements identified by reserved keywords. Structured programming is supported by if(-else) conditional execution and by do-while, while, and for iterative execution (looping). The for statement has separate initialization, testing, and reinitialization expressions, any or all of which can be omitted. break and continue can be used to leave the innermost enclosing loop statement or skip to its reinitialization. There is also a non-structured goto statement which branches directly to the designated label within the function. switch selects a case to be executed based on the value of an integer expression. card can  style",
    },
    {
        key:'41',
        category:'Machine_learning',
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/10.jpg",
        title:"heyo machine learning C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, while a static type system prevents unintended operations",
        description:"A card can As an imperative language, C uses statements to specify actions. The most common statement is an expression statement, consisting of an expression to be evaluated, followed by a semicolon; as a side effect of the evaluation, functions may be called and variables may be assigned new values. To modify the normal sequential execution of statements, C provides several control-flow statements identified by reserved keywords. Structured programming is supported by if(-else) conditional execution and by do-while, while, and for iterative execution (looping). The for statement has separate initialization, testing, and reinitialization expressions, any or all of which can be omitted. break and continue can be used to leave the innermost enclosing loop statement or skip to its reinitialization. There is also a non-structured goto statement which branches directly to the designated label within the function. switch selects a case to be executed based on the value of an integer expression. style",
    },
    {
        key:'6',
        category:"Java",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/17.jpg",
        title:"heyo excited java Java is a general-purpose programming language that is class-based",
        description:"A card can java Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere (WORA),[16] meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.[17] Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of the underlying computer architecture. The syntax of Java is similar to C and C++, but it has fewer low-level facilities than either of them. As of 2019, Java was one of the most popular programming languages in use according to GitHub,[18][19] particularly for client-server web applications, with a reported 9 million developers",
    },
    {
        key:'12',
        category:"Python",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/29.jpg",
        title:"heyo mething python Python is an interpreted, high-level, general-purpose programming language.",
        description:"A card can  style Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology.",
    },
    {
        key:'13',
        category:"C",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/10.jpg",
        title:"heyo mething c/c++ C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, while a static type system prevents unintended operations",
        description:"A As an imperative language, C uses statements to specify actions. The most common statement is an expression statement, consisting of an expression to be evaluated, followed by a semicolon; as a side effect of the evaluation, functions may be called and variables may be assigned new values. To modify the normal sequential execution of statements, C provides several control-flow statements identified by reserved keywords. Structured programming is supported by if(-else) conditional execution and by do-while, while, and for iterative execution (looping). The for statement has separate initialization, testing, and reinitialization expressions, any or all of which can be omitted. break and continue can be used to leave the innermost enclosing loop statement or skip to its reinitialization. There is also a non-structured goto statement which branches directly to the designated label within the function. switch selects a case to be executed based on the value of an integer expression. card can  style",
    },
    {
        key:'14',
        category:"DSA",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/27.jpg",
        title:"heyo mething dsa Java is a general-purpose programming language that is class-based",
        description:"A card can  style Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere (WORA),[16] meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.[17] Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of the underlying computer architecture. The syntax of Java is similar to C and C++, but it has fewer low-level facilities than either of them. As of 2019, Java was one of the most popular programming languages in use according to GitHub,[18][19] particularly for client-server web applications, with a reported 9 million developers",
    },
    {
        key:'15',
        category:'Machine_learning',
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/31.jpg",
        title:"heyo achine learning hhhhfh dhd gggggdhj djgsda sdugas ajdgh fs ghngfsgydf gagyke",
        description:"A card can  style Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology.",
    },
    {
        key:'17',
        category:"Java",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/17.jpg",
        title:"heyo mething excited java Java is a general-purpose programming language that is class-based",
        description:"A card can java Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere (WORA),[16] meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.[17] Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of the underlying computer architecture. The syntax of Java is similar to C and C++, but it has fewer low-level facilities than either of them. As of 2019, Java was one of the most popular programming languages in use according to GitHub,[18][19] particularly for client-server web applications, with a reported 9 million developers",
    },
    {
        key:'18',
        category:"Python",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/22.jpg",
        title:"heyo mething python Python i rfys an interpreted, high-level, general-purpose programming language.",
        description:"A card can  style Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere (WORA),[16] meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.[17] Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of the underlying computer architecture. The syntax of Java is similar to C and C++, but it has fewer low-level facilities than either of them. As of 2019, Java was one of the most popular programming languages in use according to GitHub,[18][19] particularly for client-server web applications, with a reported 9 million developers",
    },
    {
        key:'19',
        category:"C",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/20.jpg",
        title:"heyo mething c/c++ Java is a general-purpose programming language that is class-based",
        description:"A card can  style Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere (WORA),[16] meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.[17] Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of the underlying computer architecture. The syntax of Java is similar to C and C++, but it has fewer low-level facilities than either of them. As of 2019, Java was one of the most popular programming languages in use according to GitHub,[18][19] particularly for client-server web applications, with a reported 9 million developers",
    },
    {
        key:'20',
        category:"DSA",
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/24.jpg",
        title:"heyo mething dsa and dndnd dhd dhhd hdhd hd hfgd  rtr  ert se th ert er  ert ert",
        description:"A card can  style Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology.",
    },
    {
        key:'21',
        category:'Machine_learning',
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/19.jpg",
        title:"heyo machine learning hrfhsdf hfs ddshsd sdhfsdbf dhf fhfr ehrf erhejrfbewr whe ref",
        description:"A card can  style Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology Rather than having all of its functionality built into its core, Python was designed to be highly extensible. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach.[34] Python strives for a simpler, less-cluttered syntax and grammar while giving developers a choice in their coding methodology.",
    },
    {
        key:'22',
        category:'C++',
        link:"https://cdn.gillion.shufflehound.com/wp-content/uploads/2017/01/15.jpg",
        title:"heyo machine learning Java is a general-purpose programming language that is class-based",
        description:"A card can  style Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere (WORA),[16] meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.[17] Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of the underlying computer architecture. The syntax of Java is similar to C and C++, but it has fewer low-level facilities than either of them. As of 2019, Java was one of the most popular programming languages in use according to GitHub,[18][19] particularly for client-server web applications, with a reported 9 million developersn",
    }
]